### ISSUE TITLE
Add functionality to have multiple template types

### ISSUE THREAD

**Issue by deitChi** [deitChi/ansible-role-firewalld#8]
Add Named templates

Change from

```yaml
common:
  rich_rules:
    - 'rule protocol value="icmp" accept'
    - 'rule family="ipv4" service name="ssh" accept limit value="1/s"'
  services: []
  ports: []
```

to

```yaml
common:
  subset:
    rich_rules:
      - 'rule protocol value="icmp" accept'
      - 'rule family="ipv4" service name="ssh" accept limit value="1/s"'
    services: []
    ports: []
```

or

```yaml
common:
  rich_rules:
    subset:
      - 'rule protocol value="icmp" accept'
      - 'rule family="ipv4" service name="ssh" accept limit value="1/s"'
```
